on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      PROJECT_ID:
        required: true
        type: string

jobs:
  build-push:
    name: Build push
    runs-on: ubuntu-latest
    steps:
      - name: Build Push
        run: echo "Build and push stuff"
        
  deploy-gke:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "Deploy"