name: api-kaesekuchen

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: Deploy to environment
        required: true
        options:
          - dev-01
          - dev-02
          - dev-03
      REBUILD_IMAGE:
        type: bool
        description: Force an image rebuild
        required: false
        default: true
  pull_request:
    types: [ opened, edited ]
    paths:
      - "kaesekuchen/**"
  push:
    branches: [ "master" ]
    paths:
      - "kaesekuchen/**"

jobs:
  setup-and-pre-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - run: echo "Doing some setup and test prior to deploying kaesekuchen on ${{ inputs.env }}"
  
  build-push-deploy:
    runs-on: ubuntu-latest
    needs: setup-and-pre-tests
    environment: ${{ inputs.env }}
    steps:
      - run: echo "Build Push Deploy kaesekuchen on ${{ inputs.env }}"
